id: tensorrt-llm-deepseek
base_config:
  model: deepseek-ai/DeepSeek-V3.1
  data:
    - prompt_tokens=128,output_tokens=1024
    - prompt_tokens=1024,output_tokens=128
    - prompt_tokens=512,output_tokens=512
    - prompt_tokens=256,output_tokens=2048
    - prompt_tokens=2048,output_tokens=256
    - prompt_tokens=1024,output_tokens=1024
    - prompt_tokens=512,output_tokens=4096
    - prompt_tokens=4096,output_tokens=512
    - prompt_tokens=2048,output_tokens=2048
  llm_server_type: tensorrt-llm
configs:
  - gpu: H200:8
    region: us-east-1
    llm_server_config:
      extra_args: ["--tp_size", "8"]
  - gpu: B200:8
    client_region: us-east-1
    server_region: us-ashburn-1
    llm_server_config:
      extra_args: ["--tp_size", "8"]
